### ISSUE TITLE
Access to the repo

### ISSUE THREAD

**Issue by cfoellmann** [cfoellmann/WordPress#1]
Post a reply and I will give you access to the repo.

**Comment by thefuxia** [comment]
I would like to help. In Multilingual Press, we use JavaScript to access the site settings tabs, the next release will use output buffering to get around focus problems after hitting F5. Both solutions are really ugly, and I would love to change that in core.

**Comment by bueltge** [comment]
Praise for Initiation and help! I will also help, if I find time.
